version: "3.8"
services:
  httpd:
    build:
      context: ./httpd
    container_name: httpd
    restart: always
    ports:
    - "80:80"
    volumes:
    - ./httpd/conf:/root/conf
    - ./httpd/html:${V8_DOCUMENT_ROOT}
    - ./httpd/html:${V7_DOCUMENT_ROOT}
    env_file: .env
    networks:
      php_net:
        ipv4_address: ${HTTPD_IP_ADDRESS}

  php8:
    build:
      context: ./php8
    container_name: php8
    restart: always
    volumes:
    - ./httpd/src:${V8_DOCUMENT_ROOT}
    networks:
      php_net:
        ipv4_address: ${PHP8_IP_ADDRESS}

  php7:
    build:
      context: ./php7
    container_name: php7
    restart: always
    volumes:
    - ./httpd/src:${V7_DOCUMENT_ROOT}
    networks:
      php_net:
        ipv4_address: ${PHP7_IP_ADDRESS}

networks:
  php_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${PHP_NET_SUBNET}
